### PR TITLE
Cybix

### PR DESCRIPTION
**Pull request by DavidLantz**
Team Cybix

### CODE REVIEW

**Comment by StevenVanAcker** [comment]
sorry, I thought this was trolling at first.
Can you keep the Santa_*.jpg images intact and add yours as Cybix_*.jpg instead?

The original on the sweater picture also doesn't seem iconic :)

**Comment by DavidLantz** [comment]
New try from Cybix :)

**Comment by StevenVanAcker** [comment]
could you remove the public.pem and paste it into a comment here instead?

**Comment by DavidLantz** [comment]
Oc :)

Skickat från min iPhone

20 dec. 2019 kl. 16:51 skrev Steven Van Acker <notifications@github.com>:

﻿

could you remove the public.pem and paste it into a comment here instead?

**Comment by DavidLantz** [comment]
[public.pem.zip](https://github.com/OverTheWireOrg/advent2019-strikeapose/files/3989857/public.pem.zip)

**Comment by StevenVanAcker** [comment]
Thanks! :)

t+DxkuBIO03s3svW4RPGif/CNsBw3iHxDq9SfB0qXVJAC8/6XEpKgjDlPRaXWFgmRJmFVQn0J4EV
r7yzdoNcbHR2roFvokOatha0ff7ygxdt9e9b69miCUftk169bdRd+00KD84pmPNgmkH06HRYSdEq
jAxjsiLjpeR1YwYFMhOUxtC57GDQEwjUPoiaz1viDh7dTSvn1errD2QJVgNdKP8au011522QaJ82
3r9GjYxLChy/WC9i0+Y9pKX3hw290OrpI4Oer3QpstoEU9T3JSLdb8QKTZ2WviHbguc2kPGkTv/V
tgteI2Qo0E0VG/m9AS3f82NwEGvhXXfNTkeDLQ==

JhSNHQveUv7VVQ/WHbw1tQ/E+GF3U8Fu7q7L2tY5A0RGnkg5M6Oksh8iVW6c3Szp2yioL21A7iw1
L7VEzDRngwZrjqNe+ZjgU8OM/9TuKVs7qJyHtKANrM7WY9WX68TlhL7zPWE3Ml85d4nbWebYeiYu
lbSZLNYOyOF0YLpCAfOVacBJOCdYV2RU6Iwd8xKkGvOVVp4FCE2asBt9h9Aw+cNrcMfL81zXFKUp
zN6COYzcvuWOX8R9Flg+j4a0xaZijfMEK/PH/Th6jpxLNJ3qBscnUrhu0udpO91xw9sD+fIG42Yg
hFGi7DCpJucEpLWis1uK3HpGEO//E9odDH5tzw==

**Comment by DavidLantz** [comment]
Hi again, something was messed up with our priv key, can you send us flag again using following new pub key?:

-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuRQVnoHShT+HaWei9qoT
pwKP2LzhvtJTGCB3aiVg4tCcIIxyQin0FNk3BVIiG7Lun7Izz3aY7zeOqjg0HOEz
Gy238Ck6qpJ4wGpFH2oEb679fpZ2kJ7N0fQeNympmtMYpW0Z0lGV3CkfsjqOi9PV
mT4+Zc7+IycABumovFb0QwGZfDk68HoXLNmUkqp5Tlsm1Jw2jxig6tqzLqv4An6I
R5b6jEGhZBlf3z/eI66q5PM+3GYukdPu/0Oe68yeU7iOV2HAHJvhk90omAbQjg+C
P49vC882s9H1RJ7kvK5fp9lqwGNhx5H2Qy2Tm810VlUvppOco0SZtUPT6c3Mh4ri
FQIDAQAB
-----END PUBLIC KEY-----

sorry for being bullied……

/Cybix

Från: Steven Van Acker <notifications@github.com>
Svara till: OverTheWireOrg/advent2019-strikeapose <reply@reply.github.com>
Datum: lördag 21 december 2019 11:13
Till: OverTheWireOrg/advent2019-strikeapose <advent2019-strikeapose@noreply.github.com>
Kopia: David Lantz <david.lantz@cybix.se>, Author <author@noreply.github.com>
Ämne: Re: [OverTheWireOrg/advent2019-strikeapose] Cybix (#1)


Thanks! :)

t+DxkuBIO03s3svW4RPGif/CNsBw3iHxDq9SfB0qXVJAC8/6XEpKgjDlPRaXWFgmRJmFVQn0J4EV
r7yzdoNcbHR2roFvokOatha0ff7ygxdt9e9b69miCUftk169bdRd+00KD84pmPNgmkH06HRYSdEq
jAxjsiLjpeR1YwYFMhOUxtC57GDQEwjUPoiaz1viDh7dTSvn1errD2QJVgNdKP8au011522QaJ82
3r9GjYxLChy/WC9i0+Y9pKX3hw290OrpI4Oer3QpstoEU9T3JSLdb8QKTZ2WviHbguc2kPGkTv/V
tgteI2Qo0E0VG/m9AS3f82NwEGvhXXfNTkeDLQ==

JhSNHQveUv7VVQ/WHbw1tQ/E+GF3U8Fu7q7L2tY5A0RGnkg5M6Oksh8iVW6c3Szp2yioL21A7iw1
L7VEzDRngwZrjqNe+ZjgU8OM/9TuKVs7qJyHtKANrM7WY9WX68TlhL7zPWE3Ml85d4nbWebYeiYu
lbSZLNYOyOF0YLpCAfOVacBJOCdYV2RU6Iwd8xKkGvOVVp4FCE2asBt9h9Aw+cNrcMfL81zXFKUp
zN6COYzcvuWOX8R9Flg+j4a0xaZijfMEK/PH/Th6jpxLNJ3qBscnUrhu0udpO91xw9sD+fIG42Yg
hFGi7DCpJucEpLWis1uK3HpGEO//E9odDH5tzw==

**Pull request merged**
